### ISSUE TITLE
Transform trait to send version

### ISSUE THREAD

**Issue by odysa** [rust-lang/impl-trait-utils#29] opened 2024-02-04 17:27 UTC
`trait-variant:make` solves my problem of using async fn in pub traits. Thanks for the great work.
I wonder if it's possible to transform the trait rather than creating 2 versions since I only need the thread-safe one.

**Comment by traviscross** [comment] 2024-02-10 00:53
Closing as a duplicate of #18.

**Closed by traviscross** 2024-02-10 00:53 UTC
